# Generated by Django 4.2.2 on 2023-08-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PropertyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("시군구", models.CharField(max_length=100)),
                ("단지명", models.CharField(max_length=200)),
                ("계약연월", models.CharField(max_length=20)),
                ("전용면적", models.FloatField(verbose_name="전용면적(㎡)")),
                ("매매대금_평균", models.FloatField(verbose_name="매매대금(만원) 평균")),
                ("전세_평균", models.FloatField(verbose_name="전세(만원) 평균")),
                ("면적당_매매대금평균", models.FloatField(verbose_name="면적당 매매대금평균")),
                ("면적당_전세평균", models.FloatField(verbose_name="면적당 전세평균")),
                ("전세가율_100", models.FloatField(verbose_name="전세가율-100%")),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("전세가율_90", models.FloatField(verbose_name="전세가율-90%")),
                ("전세가율_80", models.FloatField(verbose_name="전세가율-80%")),
                ("전세가율_70", models.FloatField(verbose_name="전세가율-70%")),
                ("전세가율_60", models.FloatField(verbose_name="전세가율-60%")),
            ],
        ),
    ]
