# Generated by Django 4.2.2 on 2023-08-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("other", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="search_count", max_length=50)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
